// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaFacturacion_API.Datos;

#nullable disable

namespace SistemaFacturacion_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250405222916_Modificar nombre de columna en Persona")]
    partial class ModificarnombredecolumnaenPersona
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("aspnetroles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetroleclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuserclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuserlogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetuserroles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("aspnetusertokens", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacion_API.Datos.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ColaboradorId")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("SucursalId");

                    b.ToTable("aspnetusers", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Articulo", b =>
                {
                    b.Property<int>("ArticuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticuloId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Fecharegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Fechaultactualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Observacion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("numeric");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoArticulo")
                        .HasColumnType("integer");

                    b.Property<short?>("TipoimpuestoId")
                        .HasColumnType("smallint");

                    b.HasKey("ArticuloId");

                    b.HasIndex("SucursalId");

                    b.HasIndex("TipoimpuestoId");

                    b.ToTable("articulo");

                    b.HasDiscriminator<int>("TipoArticulo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.CategoriaProducto", b =>
                {
                    b.Property<short>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("CategoriaId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.HasKey("CategoriaId");

                    b.ToTable("categoriaproduto");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Ciudad", b =>
                {
                    b.Property<short>("CiudadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("CiudadId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("CiudadId");

                    b.ToTable("ciudad");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Colaborador", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fechaegreso")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Fechaingreso")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Salario")
                        .HasColumnType("numeric");

                    b.HasKey("PersonaId");

                    b.ToTable("colaborador");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.DetalleVenta", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalle"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ImporteExento")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ImporteGravado")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ImporteIVA")
                        .HasColumnType("numeric");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("NroItem")
                        .HasColumnType("integer");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<int>("TipoItem")
                        .HasColumnType("integer");

                    b.Property<short?>("TipoimpuestoId")
                        .IsRequired()
                        .HasColumnType("smallint");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("IdDetalle");

                    b.HasIndex("TipoimpuestoId");

                    b.HasIndex("VentaId");

                    b.ToTable("detalleventa");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Empresa", b =>
                {
                    b.Property<short>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("EmpresaId"));

                    b.Property<string>("Denominacion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Estado")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("bytea");

                    b.Property<string>("RUC")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("EmpresaId");

                    b.ToTable("empresa");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.HistorialRefreshToken", b =>
                {
                    b.Property<int>("HistorialTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistorialTokenId"));

                    b.Property<bool?>("EsActivo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("boolean")
                        .HasComputedColumnSql("(FechaExpiracion >= CURRENT_DATE)", true);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<short>("UsuarioId")
                        .HasColumnType("smallint");

                    b.HasKey("HistorialTokenId");

                    b.ToTable("HistorialRefreshToken");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Marca", b =>
                {
                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MarcaId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("MarcaId");

                    b.ToTable("marca");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.MovimientoStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Comentarios")
                        .HasColumnType("text");

                    b.Property<string>("DocumentoReferencia")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReferenciaId")
                        .HasColumnType("integer");

                    b.Property<int?>("StockId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("integer");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("StockId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("movimientos");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonaId"));

                    b.Property<string>("Apellido")
                        .HasColumnType("text");

                    b.Property<short?>("CiudadId")
                        .HasColumnType("smallint");

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Fecharegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nrodocumento")
                        .HasColumnType("text");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<short?>("TipoDocIdentidadId")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("Ultfechaactualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UsuarioIdMod")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioRegistro")
                        .HasColumnType("text");

                    b.HasKey("PersonaId");

                    b.HasIndex("CiudadId");

                    b.HasIndex("SucursalId");

                    b.HasIndex("TipoDocIdentidadId");

                    b.ToTable("persona");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.PrecioPromocional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("ArticuloId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("PrecioPromocion")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.ToTable("preciopromocional");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Presentacion", b =>
                {
                    b.Property<short>("PresentacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("PresentacionId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PresentacionId");

                    b.ToTable("presentacion");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Rango_Timbrados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NroActual")
                        .HasColumnType("integer");

                    b.Property<int>("Nro_Establecimiento")
                        .HasColumnType("integer");

                    b.Property<int>("Nro_PuntoExp")
                        .HasColumnType("integer");

                    b.Property<int>("RangoDesde")
                        .HasColumnType("integer");

                    b.Property<int>("RangoHasta")
                        .HasColumnType("integer");

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer");

                    b.Property<short>("TimbradoId")
                        .HasColumnType("smallint");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.HasIndex("TimbradoId");

                    b.ToTable("rango_timbrados");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaGrab")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("JwtId")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("refreshtokens");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("stock");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Sucursal", b =>
                {
                    b.Property<int>("SucursalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SucursalId"));

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<short>("EmpresaId")
                        .HasColumnType("smallint");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("SucursalId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("sucursales");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Timbrado", b =>
                {
                    b.Property<short>("TimbradoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("TimbradoId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<DateTime>("FechaFinVigencia")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicioVigencia")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TipoTimbrado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("TimbradoId");

                    b.ToTable("timbrado");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.TipoDocumentoIdentidad", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("tipodocumentoidentidad");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.TipoImpuesto", b =>
                {
                    b.Property<short>("TipoimpuestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("TipoimpuestoId"));

                    b.Property<decimal>("Baseimponible")
                        .HasColumnType("numeric");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Porcentajeiva")
                        .HasColumnType("numeric");

                    b.HasKey("TipoimpuestoId");

                    b.ToTable("tipoimpuesto");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.TipoServicio", b =>
                {
                    b.Property<short>("TipoServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("TipoServicioId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.HasKey("TipoServicioId");

                    b.ToTable("tiposervicio");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Ubicacion", b =>
                {
                    b.Property<int>("UbicacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UbicacionId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer");

                    b.HasKey("UbicacionId");

                    b.HasIndex("SucursalId");

                    b.ToTable("ubicacion");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.UnidadMedida", b =>
                {
                    b.Property<short>("UnidadMedidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("UnidadMedidaId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.HasKey("UnidadMedidaId");

                    b.ToTable("unidadmedida");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int?>("ColaboradorId")
                        .HasColumnType("integer");

                    b.Property<string>("EsAutoimprenta")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<short>("Establecimiento")
                        .HasColumnType("smallint");

                    b.Property<string>("Estado")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NroFactura")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<short>("PuntoExpedicion")
                        .HasColumnType("smallint");

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer");

                    b.Property<short>("TimbradoId")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalIVA")
                        .HasColumnType("numeric");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioIdAnulacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioIdModificacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioIdRegistro")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("SucursalId");

                    b.HasIndex("TimbradoId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("venta");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Producto", b =>
                {
                    b.HasBaseType("SistemaFacturacion_Model.Modelos.Articulo");

                    b.Property<short?>("CategoriaId")
                        .HasColumnType("smallint");

                    b.Property<string>("Codigobarra")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<short?>("Idpresentacion")
                        .HasColumnType("smallint");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("numeric");

                    b.Property<int>("Stockminimo")
                        .HasColumnType("integer");

                    b.Property<short?>("Unidadmedidanro")
                        .HasColumnType("smallint");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Idpresentacion");

                    b.HasIndex("MarcaId");

                    b.HasIndex("Unidadmedidanro");

                    b.ToTable("articulo");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Servicio", b =>
                {
                    b.HasBaseType("SistemaFacturacion_Model.Modelos.Articulo");

                    b.Property<short>("TipoServicioId")
                        .HasColumnType("smallint");

                    b.HasIndex("TipoServicioId");

                    b.ToTable("articulo");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SistemaFacturacion_API.Datos.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SistemaFacturacion_API.Datos.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFacturacion_API.Datos.Usuario", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SistemaFacturacion_API.Datos.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaFacturacion_API.Datos.Usuario", b =>
                {
                    b.HasOne("SistemaFacturacion_Model.Modelos.Colaborador", "Colaborador")
                        .WithOne()
                        .HasForeignKey("SistemaFacturacion_API.Datos.Usuario", "ColaboradorId");

                    b.HasOne("SistemaFacturacion_Model.Modelos.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId");

                    b.Navigation("Colaborador");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Articulo", b =>
                {
                    b.HasOne("SistemaFacturacion_Model.Modelos.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId");

                    b.HasOne("SistemaFacturacion_Model.Modelos.TipoImpuesto", "TipoImpuesto")
                        .WithMany()
                        .HasForeignKey("TipoimpuestoId");

                    b.Navigation("Sucursal");

                    b.Navigation("TipoImpuesto");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Colaborador", b =>
                {
                    b.HasOne("SistemaFacturacion_Model.Modelos.Persona", "Persona")
                        .WithOne("Colaborador")
                        .HasForeignKey("SistemaFacturacion_Model.Modelos.Colaborador", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.DetalleVenta", b =>
                {
                    b.HasOne("SistemaFacturacion_Model.Modelos.TipoImpuesto", "TipoImpuesto")
                        .WithMany()
                        .HasForeignKey("TipoimpuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFacturacion_Model.Modelos.Venta", "Venta")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoImpuesto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.MovimientoStock", b =>
                {
                    b.HasOne("SistemaFacturacion_Model.Modelos.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFacturacion_Model.Modelos.Stock", null)
                        .WithMany("Movimientos")
                        .HasForeignKey("StockId");

                    b.HasOne("SistemaFacturacion_Model.Modelos.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Persona", b =>
                {
                    b.HasOne("SistemaFacturacion_Model.Modelos.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadId");

                    b.HasOne("SistemaFacturacion_Model.Modelos.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId");

                    b.HasOne("SistemaFacturacion_Model.Modelos.TipoDocumentoIdentidad", "TipoDocumentoIdentidad")
                        .WithMany()
                        .HasForeignKey("TipoDocIdentidadId");

                    b.Navigation("Ciudad");

                    b.Navigation("Sucursal");

                    b.Navigation("TipoDocumentoIdentidad");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.PrecioPromocional", b =>
                {
                    b.HasOne("SistemaFacturacion_Model.Modelos.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Rango_Timbrados", b =>
                {
                    b.HasOne("SistemaFacturacion_Model.Modelos.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFacturacion_Model.Modelos.Timbrado", "Timbrado")
                        .WithMany("Rango_Timbrados")
                        .HasForeignKey("TimbradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");

                    b.Navigation("Timbrado");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Stock", b =>
                {
                    b.HasOne("SistemaFacturacion_Model.Modelos.Producto", "Producto")
                        .WithMany("Stocks")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFacturacion_Model.Modelos.Ubicacion", "Ubicacion")
                        .WithMany("Stocks")
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Sucursal", b =>
                {
                    b.HasOne("SistemaFacturacion_Model.Modelos.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Ubicacion", b =>
                {
                    b.HasOne("SistemaFacturacion_Model.Modelos.Sucursal", "Sucursal")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Venta", b =>
                {
                    b.HasOne("SistemaFacturacion_Model.Modelos.Persona", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFacturacion_Model.Modelos.Colaborador", "Vendedor")
                        .WithMany()
                        .HasForeignKey("ColaboradorId");

                    b.HasOne("SistemaFacturacion_Model.Modelos.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFacturacion_Model.Modelos.Timbrado", "Timbrado")
                        .WithMany()
                        .HasForeignKey("TimbradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFacturacion_Model.Modelos.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId");

                    b.Navigation("Cliente");

                    b.Navigation("Sucursal");

                    b.Navigation("Timbrado");

                    b.Navigation("Ubicacion");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Producto", b =>
                {
                    b.HasOne("SistemaFacturacion_Model.Modelos.CategoriaProducto", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("SistemaFacturacion_Model.Modelos.Presentacion", "Presentacion")
                        .WithMany("Productos")
                        .HasForeignKey("Idpresentacion");

                    b.HasOne("SistemaFacturacion_Model.Modelos.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId");

                    b.HasOne("SistemaFacturacion_Model.Modelos.UnidadMedida", "UnidadMedida")
                        .WithMany("Productos")
                        .HasForeignKey("Unidadmedidanro");

                    b.Navigation("Categoria");

                    b.Navigation("Marca");

                    b.Navigation("Presentacion");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Servicio", b =>
                {
                    b.HasOne("SistemaFacturacion_Model.Modelos.TipoServicio", "TipoServicio")
                        .WithMany()
                        .HasForeignKey("TipoServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoServicio");
                });

            modelBuilder.Entity("SistemaFacturacion_API.Datos.Usuario", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Persona", b =>
                {
                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Presentacion", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Stock", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Sucursal", b =>
                {
                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Timbrado", b =>
                {
                    b.Navigation("Rango_Timbrados");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Ubicacion", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.UnidadMedida", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Venta", b =>
                {
                    b.Navigation("DetalleVenta");
                });

            modelBuilder.Entity("SistemaFacturacion_Model.Modelos.Producto", b =>
                {
                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
