// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaFacturacionWeb.Datos;

#nullable disable

namespace SistemaFacturacionWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231103142537_CargarDatosALaTablaVilla")]
    partial class CargarDatosALaTablaVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaFacturacionWeb.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagenURL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MetrosCuadratos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("integer");

                    b.Property<double>("Tarifa")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalle = "Detalle villa real",
                            FechaCreacion = new DateTime(2023, 11, 3, 11, 25, 37, 655, DateTimeKind.Local).AddTicks(2919),
                            ImagenURL = "",
                            MetrosCuadratos = 50,
                            Nombre = "Villa Real",
                            Ocupantes = 5,
                            Tarifa = 0.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalle = "Detalle villa nueva 2",
                            FechaCreacion = new DateTime(2023, 11, 3, 11, 25, 37, 655, DateTimeKind.Local).AddTicks(3010),
                            ImagenURL = "",
                            MetrosCuadratos = 60,
                            Nombre = "Villa Nueva 2 ",
                            Ocupantes = 10,
                            Tarifa = 0.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
